# This is a basic workflow to help you get started with Actions

name: Build and publish graphhopper image

on:
  schedule:
     - cron: 0 1 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      rebuild-all:
        type: boolean
        description: rebuild all images

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          REBUILD_ALL: ${{ github.event.inputs.rebuild-all == 'true' }}
        run: ./.github/build-and-upload-v2.sh
